export const reducerType = {
    HEROES_FETCHING: "HEROES_FETCHING",
    HEROES_FETCHED: "HEROES_FETCHED",
    HEROES_FETCHING_ERROR: "HEROES_FETCHING_ERROR",
    FILTERS_FETCHING: "FILTERS_FETCHING",
    FILTERS_FETCHED: "FILTERS_FETCHED",
    FILTERS_FETCHING_ERROR: "FILTERS_FETCHING_ERROR",
}